"""Edit Contact model and route

Revision ID: 73778e9f2b5f
Revises: 
Create Date: 2026-03-10 10:34:17.586347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73778e9f2b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
