"""Email feedback on Contact model

Revision ID: a04f34e68939
Revises: 73778e9f2b5f
Create Date: 2026-03-10 11:01:27.608924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04f34e68939'
down_revision = '73778e9f2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Make column nullable so migration can succeed
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # 2. Fill NULL emails with a placeholder (or leave as NULL if acceptable)
    op.execute("UPDATE contacts SET email = 'unknown@example.com' WHERE email IS NULL")

    # Optional: If you really want NOT NULL now, add this after filling
    # with op.batch_alter_table('contacts', schema=None) as batch_op:
    #     batch_op.alter_column('email', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
